(() => {
  'use strict';
  const $ = (id) => document.getElementById(id);
  const ui = { intro:$('intro'), game:$('game'), result:$('result'), start:$('start'), back:$('back'), next:$('next'), restart:$('restart'), phase:$('phase'), title:$('round-title'), progress:$('progress-fill'), progressLabel:$('progress-label'), prompt:$('prompt'), cards:$('cards'), picked:$('picked-label'), winners:$('winners'), note:$('load-note'), pickerWrap:$('csv-picker-wrap'), picker:$('csv-picker') };
  let members=[], rounds=[], stage=0, index=0, picked=new Set(), history=[];
  const stageNames=['予選','一次通過','準決勝'];
  const esc=(s)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const shuffle=(a)=>{for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
  const imagePath=(m)=>`images/${encodeURIComponent(m.group)}/${encodeURIComponent(m.name)}.jpg`;
  async function load(){try{const r=await fetch('members.csv');if(!r.ok)throw Error('members.csv を開けません');const text=(await r.text()).replace(/^\uFEFF/,'');members=parseCSV(text).filter(x=>x.name&&x.group);ui.note.textContent=`${members.length}人のメンバーを読み込みました`;ui.start.disabled=!members.length}catch(e){ui.note.textContent='PC上で直接開いている場合は、下から members.csv を選んでください。';ui.pickerWrap.classList.remove('hidden');ui.start.disabled=true}}
  ui.picker.addEventListener('change',async()=>{const f=ui.picker.files&&ui.picker.files[0];if(!f)return;try{members=parseCSV((await f.text()).replace(/^\uFEFF/,'' )).filter(x=>x.name&&x.group);ui.note.textContent=members.length?`${members.length}人を読み込みました。写真はimagesフォルダから表示します。`:'CSVにメンバーが見つかりません';ui.start.disabled=!members.length}catch(e){ui.note.textContent='CSVを読み込めませんでした。members.csvを選んでください。';ui.start.disabled=true}});
  function parseCSV(s){const rows=[];let row=[],cell='',q=false;for(let i=0;i<s.length;i++){const c=s[i];if(q){if(c==='"'&&s[i+1]==='"'){cell+='"';i++}else if(c==='"')q=false;else cell+=c}else if(c==='"')q=true;else if(c===','){row.push(cell);cell=''}else if(c==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell=''}else cell+=c}if(cell||row.length){row.push(cell.replace(/\r$/,''));rows.push(row)}const h=rows.shift()||[];return rows.map(r=>Object.fromEntries(h.map((k,i)=>[k,(r[i]||'').trim()]))) }
  function makeGroups(list){const a=shuffle([...list]);const groups=[];while(a.length)groups.push(a.splice(0,4));return groups}
  function begin(){rounds=[{name:'予選',groups:makeGroups(members),answers:Array(members.length).fill(null)}];stage=0;index=0;history=[];showGame()}
  function showGame(){ui.intro.classList.add('hidden');ui.result.classList.add('hidden');ui.game.classList.remove('hidden');renderQuestion()}
  function renderQuestion(){const round=rounds[stage],group=round.groups[index];picked=new Set(round.answers[index]||[]);const total=round.groups.length;ui.phase.textContent=`STAGE 0${stage+1}　${stageNames[stage]||round.name}`;ui.title.textContent=stage===0?'まずは全員をチェック':stage===1?'一次通過メンバーを選ぼう':stage===2?'決勝へ進むメンバーを選ぼう':'好きな人を選ぼう';ui.progress.style.width=`${((index+1)/total)*100}%`;ui.progressLabel.textContent=`${index+1} / ${total} グループ`;ui.prompt.textContent='気になる人を0〜3人選んでください';ui.cards.innerHTML=group.map((m,i)=>cardHTML(m,i)).join('');ui.cards.querySelectorAll('.card').forEach((el,i)=>el.addEventListener('click',()=>toggle(i)));ui.picked.textContent=`${picked.size}人選択中`;ui.next.disabled=false;ui.next.innerHTML=index===total-1?'この段階を完了 <b>✓</b>':'次へ <b>→</b>';ui.back.disabled=history.length===0;ui.back.style.visibility=history.length?'visible':'hidden'}
  function cardHTML(m,i){return `<button class="card ${picked.has(i)?'selected':''}" type="button"><span class="check">✓</span><div class="photo"><img loading="lazy" src="${esc(imagePath(m))}" alt="${esc(m.name)}" onerror="this.remove();this.parentElement.innerHTML='<span class=&quot;placeholder&quot;>${esc((m.name||'?').slice(0,1))}</span>'"></div><div class="card-info"><div class="card-name">${esc(m.name)}</div><div class="card-group">${esc(m.group)}</div></div></button>`}
  function toggle(i){if(picked.has(i))picked.delete(i);else if(picked.size<3)picked.add(i);else return;ui.cards.querySelectorAll('.card').forEach((el,n)=>el.classList.toggle('selected',picked.has(n)));ui.picked.textContent=`${picked.size}人選択中`}
  function saveAnswer(){rounds[stage].answers[index]=[...picked]}
  function next(){saveAnswer();if(index<rounds[stage].groups.length-1){history.push({stage,index});index++;renderQuestion();return}finishStage()}
  function finishStage(){const r=rounds[stage];
    const advancing=[];r.groups.forEach((g,gi)=>(r.answers[gi]||[]).forEach(i=>advancing.push(g[i])));
    if(!advancing.length){alert('この段階で選ばれた人がいません。戻って、各グループから1人以上選んでください。');index=Math.max(0,r.groups.length-1);renderQuestion();return}
    const unique=[...new Map(advancing.map(m=>[m.name+'\u0000'+m.group,m])).values()];
    if(stage===0){rounds.push({name:'一次通過',groups:makeGroups(unique),answers:[]});stage++;index=0;showGame();return}
    if(stage===1){rounds.push({name:'準決勝',groups:makeGroups(unique),answers:[]});stage++;index=0;showGame();return}
    if(stage===2){if(unique.length<9){alert(`TOP9を作るため、準決勝では9人以上を選んでください（現在${unique.length}人）。戻って選び直してください。`);index=Math.max(0,r.groups.length-1);renderQuestion();return}if(unique.length>18){rounds[2]={name:'準決勝',groups:makeGroups(unique),answers:[]};index=0;showGame();return}startFinal(unique);return}
  }
  function startFinal(finalists){const matchups=Array.from({length:9},()=>[]);shuffle(finalists).forEach((m,i)=>matchups[i%9].push(m));rounds.push({name:'決勝',groups:matchups,answers:Array(matchups.length).fill(null),final:true});stage=3;index=0;renderFinal()}
  function renderFinal(){const r=rounds[stage],g=r.groups[index];picked=new Set(r.answers[index]||[]);ui.game.classList.remove('hidden');ui.phase.textContent='STAGE 04　決勝';ui.title.textContent='TOP9を決めよう';ui.progress.style.width=`${((index+1)/r.groups.length)*100}%`;ui.progressLabel.textContent=`${index+1} / ${r.groups.length} 試合`;ui.prompt.textContent='この対決で好きな方を1人選んでください';ui.cards.innerHTML=g.map((m,i)=>cardHTML(m,i)).join('');ui.cards.querySelectorAll('.card').forEach((el,i)=>el.addEventListener('click',()=>{picked=new Set([i]);ui.cards.querySelectorAll('.card').forEach((c,n)=>c.classList.toggle('selected',n===i));ui.picked.textContent='1人選択中';ui.next.disabled=false}));ui.picked.textContent=picked.size?'1人選択中':'選択してください';ui.next.disabled=!picked.size;ui.next.innerHTML=index===r.groups.length-1?'決定 <b>✓</b>':'次の対決へ <b>→</b>';ui.back.style.visibility=history.length?'visible':'hidden'}
  function nextFinal(){const r=rounds[stage];r.answers[index]=[...picked];if(index<r.groups.length-1){history.push({stage,index});index++;renderFinal();return}const winners=[];r.groups.forEach((g,gi)=>{const i=(r.answers[gi]||[])[0];if(i!==undefined)winners.push(g[i])});showResult(winners)}
  function showResult(winners){ui.game.classList.add('hidden');ui.result.classList.remove('hidden');ui.winners.innerHTML=winners.slice(0,9).map((m,i)=>`<article class="winner"><div class="photo"><img loading="lazy" src="${esc(imagePath(m))}" alt="${esc(m.name)}" onerror="this.remove();this.parentElement.innerHTML='<span class=&quot;placeholder&quot;>${esc(m.name.slice(0,1))}</span>'"></div><div class="winner-label">TOP ${String(i+1).padStart(2,'0')}</div><div class="card-info"><div class="card-name">${esc(m.name)}</div><div class="card-group">${esc(m.group)}</div></div></article>`).join('')}
  function back(){if(!history.length)return;const h=history.pop();stage=h.stage;index=h.index;if(stage===3)renderFinal();else renderQuestion()}
  ui.start.addEventListener('click',begin);ui.next.addEventListener('click',()=>stage===3?nextFinal():next());ui.back.addEventListener('click',back);ui.restart.addEventListener('click',()=>{ui.result.classList.add('hidden');ui.intro.classList.remove('hidden')});load();
})();
